### ISSUE TITLE
How to tilt the x-axis index mark in ggthemes?

### ISSUE THREAD

**Issue by xiasummer** [jrnold/ggthemes#92] opened 2018-06-17 06:59 UTC
Hi, I have date as x-axis value.
I like ggthemes gdocs theme.
But when I use ggthemes_gdocs together with theme(axis.title.x = element_text(angle = 90)), the latter one won't take effect.

So what should I do?

**Comment by tomhopper** [comment] 2018-06-18 11:02
You should provide a minimal reproducible example (https://stackoverflow.com/a/5963610) so that the rest of us can see and diagnose the problem.

**Comment by jrnold** [comment] 2018-06-19 00:04
I'm not sure exactly what you are trying to do with this. Follow @tomhopper 's advice on a minimal reproducible example. I don't think this is a problem with the theme per se. It probably means trying different values in theme: http://ggplot2.tidyverse.org/reference/theme.html.  You may also be thinking of `axis.text.x` as the element you want to alter.

**Comment by jrnold** [comment] 2018-06-26 23:54
I'm closing this because it doesn't seem to be a bug.

**Closed by jrnold** 2018-06-26 23:54 UTC
Labels: question
